---
title: "GroupProject work File"
author: "Christopher Hishmeh"
date: "4/29/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r Data Cleaning and Decomp}
data <- read.csv("credit.csv")
library(fpp3)
library(lubridate)
year <- c()
for(i in 1:41){
  year[i] <- 1980+i
}
year <- rep(year,12)
year <- year[order(year, decreasing=TRUE)]

data$date <- paste(year,data$date)
data$date <- ym(data$date)

data$date<-yearmonth(data$date)

colnames(data)[2] <- "date"

colnames(data)[1] <- "credit"


data <- tsibble(data, index=date)


data %>% 
  model(classical_decomposition(credit, type = 'additive')) %>% 
  components() %>% 
  autoplot()
autoplot(data)


```



```{r Models}
lambda <- data %>% 
  features(data$credit, features = guerrero) %>% 
  pull(lambda_guerrero)

data <- data %>% 
  mutate(bc = box_cox(data$credit, lambda))

holdout <- tail(data, 12)
train <-  head(data, nrow(data)-12)

data %>% 
  autoplot(bc)
data %>%
  gg_tsdisplay(bc)

fit <- train %>% 
  model(
    TSLM(bc~trend()),
    arima = ARIMA(bc),
    ets = ETS(bc),
    nnet = NNETAR(bc)
  )
fit%>% 
  forecast(h = 3, times = 0) %>% 
  accuracy(data) %>% 
  arrange(RMSE)

fit <- data%>%
  model(TSLM(bc~trend()))

fit %>%
  forecast(holdout, times=100)%>%
  autoplot(data)

fit %>%
  forecast(data)%>%
  autoplot(data)

pred <- fit %>%
  forecast(h=12)
predictions <- inv_box_cox(pred$.mean, lambda)
predictions

write.csv(predictions, file= "predictions.csv")

gg_tsresiduals(fit)


report(fit)
```


